// ---------------------------------------------------------------------------
// A curated list of ~100 real, well-known AI tools/products, used to seed the
// homepage tools table. `domain` is the tool's real website — used to fetch
// its real brand logo (via Clearbit's logo API, keyed by domain) instead of
// a generic placeholder icon.
// ---------------------------------------------------------------------------

export interface RealTool {
  name: string;
  domain: string;
  task: string;
  category: string;
  pricing: "Free" | "Freemium" | "Paid" | "Free Trial";
  country: string;
}

export const REAL_TOOLS: RealTool[] = [
  { name: "ChatGPT", domain: "openai.com", task: "Chat & general assistant", category: "Productivity", pricing: "Freemium", country: "US" },
  { name: "Claude", domain: "claude.ai", task: "Chat & general assistant", category: "Productivity", pricing: "Freemium", country: "US" },
  { name: "Gemini", domain: "gemini.google.com", task: "Chat & general assistant", category: "Productivity", pricing: "Freemium", country: "US" },
  { name: "Perplexity", domain: "perplexity.ai", task: "AI-powered search", category: "Research", pricing: "Freemium", country: "US" },
  { name: "Microsoft Copilot", domain: "copilot.microsoft.com", task: "Chat & general assistant", category: "Productivity", pricing: "Freemium", country: "US" },
  { name: "Midjourney", domain: "midjourney.com", task: "Generate images", category: "Image Generation", pricing: "Paid", country: "US" },
  { name: "Stable Diffusion", domain: "stability.ai", task: "Generate images", category: "Image Generation", pricing: "Free Trial", country: "UK" },
  { name: "Leonardo.Ai", domain: "leonardo.ai", task: "Generate images", category: "Image Generation", pricing: "Freemium", country: "AU" },
  { name: "Ideogram", domain: "ideogram.ai", task: "Generate images with text", category: "Image Generation", pricing: "Freemium", country: "CA" },
  { name: "Adobe Firefly", domain: "adobe.com", task: "Generate images", category: "Image Generation", pricing: "Freemium", country: "US" },
  { name: "Recraft", domain: "recraft.ai", task: "Generate vector art", category: "Image Generation", pricing: "Freemium", country: "US" },
  { name: "Runway", domain: "runwayml.com", task: "Generate & edit video", category: "Video", pricing: "Freemium", country: "US" },
  { name: "Pika", domain: "pika.art", task: "Generate video", category: "Video", pricing: "Freemium", country: "US" },
  { name: "Luma Dream Machine", domain: "lumalabs.ai", task: "Generate video", category: "Video", pricing: "Freemium", country: "US" },
  { name: "Synthesia", domain: "synthesia.io", task: "Generate AI avatar videos", category: "Video", pricing: "Paid", country: "UK" },
  { name: "HeyGen", domain: "heygen.com", task: "Generate AI avatar videos", category: "Video", pricing: "Freemium", country: "US" },
  { name: "Colossyan", domain: "colossyan.com", task: "Generate training videos", category: "Video", pricing: "Freemium", country: "UK" },
  { name: "Tavus", domain: "tavus.io", task: "Generate personalized video", category: "Video", pricing: "Paid", country: "US" },
  { name: "Opus Clip", domain: "opus.pro", task: "Repurpose long videos into clips", category: "Video", pricing: "Freemium", country: "US" },
  { name: "Vidyo.ai", domain: "vidyo.ai", task: "Repurpose long videos into clips", category: "Video", pricing: "Freemium", country: "IN" },
  { name: "CapCut", domain: "capcut.com", task: "Edit short-form video", category: "Video", pricing: "Freemium", country: "SG" },
  { name: "Kapwing", domain: "kapwing.com", task: "Edit video collaboratively", category: "Video", pricing: "Freemium", country: "US" },
  { name: "Descript", domain: "descript.com", task: "Edit video & podcasts by text", category: "Video", pricing: "Freemium", country: "US" },
  { name: "ElevenLabs", domain: "elevenlabs.io", task: "Generate a voiceover", category: "Audio", pricing: "Freemium", country: "US" },
  { name: "Murf AI", domain: "murf.ai", task: "Generate a voiceover", category: "Audio", pricing: "Freemium", country: "US" },
  { name: "Play.ht", domain: "play.ht", task: "Generate a voiceover", category: "Audio", pricing: "Freemium", country: "US" },
  { name: "Resemble AI", domain: "resemble.ai", task: "Clone a voice", category: "Audio", pricing: "Paid", country: "US" },
  { name: "Speechify", domain: "speechify.com", task: "Text to speech", category: "Audio", pricing: "Freemium", country: "US" },
  { name: "Suno", domain: "suno.com", task: "Generate music", category: "Audio", pricing: "Freemium", country: "US" },
  { name: "Udio", domain: "udio.com", task: "Generate music", category: "Audio", pricing: "Freemium", country: "US" },
  { name: "AIVA", domain: "aiva.ai", task: "Compose soundtrack music", category: "Audio", pricing: "Freemium", country: "LU" },
  { name: "Krisp", domain: "krisp.ai", task: "Remove background noise on calls", category: "Audio", pricing: "Freemium", country: "US" },
  { name: "Podcastle", domain: "podcastle.ai", task: "Record & edit podcasts", category: "Audio", pricing: "Freemium", country: "US" },
  { name: "Notion AI", domain: "notion.so", task: "Summarize a document", category: "Productivity", pricing: "Freemium", country: "US" },
  { name: "Jasper", domain: "jasper.ai", task: "Generate marketing copy", category: "Writing", pricing: "Paid", country: "US" },
  { name: "Copy.ai", domain: "copy.ai", task: "Generate marketing copy", category: "Writing", pricing: "Freemium", country: "US" },
  { name: "Writesonic", domain: "writesonic.com", task: "Generate marketing copy", category: "Writing", pricing: "Freemium", country: "US" },
  { name: "Grammarly", domain: "grammarly.com", task: "Fix grammar & tone", category: "Writing", pricing: "Freemium", country: "US" },
  { name: "QuillBot", domain: "quillbot.com", task: "Paraphrase text", category: "Writing", pricing: "Freemium", country: "US" },
  { name: "Rytr", domain: "rytr.me", task: "Generate marketing copy", category: "Writing", pricing: "Freemium", country: "US" },
  { name: "Sudowrite", domain: "sudowrite.com", task: "Write fiction", category: "Writing", pricing: "Paid", country: "US" },
  { name: "GitHub Copilot", domain: "github.com", task: "Write & complete code", category: "Coding", pricing: "Freemium", country: "US" },
  { name: "Cursor", domain: "cursor.com", task: "Write & complete code", category: "Coding", pricing: "Freemium", country: "US" },
  { name: "Replit", domain: "replit.com", task: "Build & deploy an app", category: "Coding", pricing: "Freemium", country: "US" },
  { name: "Windsurf", domain: "windsurf.com", task: "Write & complete code", category: "Coding", pricing: "Freemium", country: "US" },
  { name: "v0", domain: "v0.dev", task: "Generate UI from a prompt", category: "Coding", pricing: "Freemium", country: "US" },
  { name: "Bolt", domain: "bolt.new", task: "Build a web app from a prompt", category: "Coding", pricing: "Freemium", country: "US" },
  { name: "Lovable", domain: "lovable.dev", task: "Build a web app from a prompt", category: "Coding", pricing: "Freemium", country: "SE" },
  { name: "Tabnine", domain: "tabnine.com", task: "Write & complete code", category: "Coding", pricing: "Freemium", country: "IL" },
  { name: "Zapier", domain: "zapier.com", task: "Automate a workflow", category: "Productivity", pricing: "Freemium", country: "US" },
  { name: "Make", domain: "make.com", task: "Automate a workflow", category: "Productivity", pricing: "Freemium", country: "IL" },
  { name: "n8n", domain: "n8n.io", task: "Automate a workflow", category: "Productivity", pricing: "Freemium", country: "DE" },
  { name: "Gamma", domain: "gamma.app", task: "Generate a slide deck", category: "Productivity", pricing: "Freemium", country: "US" },
  { name: "Beautiful.ai", domain: "beautiful.ai", task: "Generate a slide deck", category: "Productivity", pricing: "Freemium", country: "US" },
  { name: "Tome", domain: "tome.app", task: "Generate a slide deck", category: "Productivity", pricing: "Freemium", country: "US" },
  { name: "Canva Magic Studio", domain: "canva.com", task: "Design social media posts", category: "Image Generation", pricing: "Freemium", country: "AU" },
  { name: "Framer", domain: "framer.com", task: "Build a website", category: "Coding", pricing: "Freemium", country: "NL" },
  { name: "Otter.ai", domain: "otter.ai", task: "Transcribe a meeting", category: "Productivity", pricing: "Freemium", country: "US" },
  { name: "Fireflies.ai", domain: "fireflies.ai", task: "Transcribe a meeting", category: "Productivity", pricing: "Freemium", country: "US" },
  { name: "Fathom", domain: "fathom.video", task: "Transcribe a meeting", category: "Productivity", pricing: "Free", country: "US" },
  { name: "tl;dv", domain: "tldv.io", task: "Transcribe a meeting", category: "Productivity", pricing: "Freemium", country: "US" },
  { name: "Superhuman", domain: "superhuman.com", task: "Triage your inbox", category: "Productivity", pricing: "Paid", country: "US" },
  { name: "Motion", domain: "usemotion.com", task: "Plan your calendar", category: "Productivity", pricing: "Paid", country: "US" },
  { name: "Reclaim.ai", domain: "reclaim.ai", task: "Plan your calendar", category: "Productivity", pricing: "Freemium", country: "US" },
  { name: "Character.AI", domain: "character.ai", task: "Chat with a character", category: "Productivity", pricing: "Freemium", country: "US" },
  { name: "Poe", domain: "poe.com", task: "Chat with multiple models", category: "Productivity", pricing: "Freemium", country: "US" },
  { name: "You.com", domain: "you.com", task: "AI-powered search", category: "Research", pricing: "Freemium", country: "US" },
  { name: "Phind", domain: "phind.com", task: "AI-powered search for developers", category: "Research", pricing: "Freemium", country: "US" },
  { name: "Hugging Face", domain: "huggingface.co", task: "Host & run open models", category: "Coding", pricing: "Freemium", country: "US" },
  { name: "Replicate", domain: "replicate.com", task: "Run AI models via API", category: "Coding", pricing: "Free Trial", country: "US" },
  { name: "Together AI", domain: "together.ai", task: "Run AI models via API", category: "Coding", pricing: "Free Trial", country: "US" },
  { name: "Groq", domain: "groq.com", task: "Run AI models via API", category: "Coding", pricing: "Free Trial", country: "US" },
  { name: "Mistral AI", domain: "mistral.ai", task: "Chat & general assistant", category: "Productivity", pricing: "Freemium", country: "FR" },
  { name: "DeepSeek", domain: "deepseek.com", task: "Chat & general assistant", category: "Productivity", pricing: "Freemium", country: "CN" },
  { name: "Cohere", domain: "cohere.com", task: "Run AI models via API", category: "Coding", pricing: "Free Trial", country: "CA" },
  { name: "Photoroom", domain: "photoroom.com", task: "Remove background from an image", category: "Image Generation", pricing: "Freemium", country: "FR" },
  { name: "Remove.bg", domain: "remove.bg", task: "Remove background from an image", category: "Image Generation", pricing: "Freemium", country: "DE" },
  { name: "Clipdrop", domain: "clipdrop.co", task: "Edit product photos", category: "Image Generation", pricing: "Freemium", country: "FR" },
  { name: "Topaz Photo AI", domain: "topazlabs.com", task: "Upscale & sharpen photos", category: "Image Generation", pricing: "Paid", country: "US" },
  { name: "Pictory", domain: "pictory.ai", task: "Turn text into video", category: "Video", pricing: "Freemium", country: "US" },
  { name: "InVideo", domain: "invideo.io", task: "Turn text into video", category: "Video", pricing: "Freemium", country: "IN" },
  { name: "D-ID", domain: "d-id.com", task: "Animate a photo into a talking avatar", category: "Video", pricing: "Freemium", country: "IL" },
  { name: "Figma AI", domain: "figma.com", task: "Prototype a product interface", category: "Productivity", pricing: "Freemium", country: "US" },
  { name: "Uizard", domain: "uizard.io", task: "Turn a sketch into a UI design", category: "Productivity", pricing: "Freemium", country: "SE" },
  { name: "Looka", domain: "looka.com", task: "Generate a logo", category: "Image Generation", pricing: "Paid", country: "CA" },
  { name: "Brandmark", domain: "brandmark.io", task: "Generate a logo", category: "Image Generation", pricing: "Paid", country: "AU" },
  { name: "Namelix", domain: "namelix.com", task: "Generate a business name", category: "Marketing", pricing: "Free", country: "AU" },
  { name: "Tidio", domain: "tidio.com", task: "Build a customer support chatbot", category: "Customer Support", pricing: "Freemium", country: "PL" },
  { name: "Intercom Fin", domain: "intercom.com", task: "Build a customer support chatbot", category: "Customer Support", pricing: "Paid", country: "US" },
  { name: "Drift", domain: "drift.com", task: "Build a customer support chatbot", category: "Customer Support", pricing: "Paid", country: "US" },
  { name: "Ada", domain: "ada.cx", task: "Build a customer support chatbot", category: "Customer Support", pricing: "Paid", country: "CA" },
  { name: "HubSpot AI", domain: "hubspot.com", task: "Generate marketing copy", category: "Marketing", pricing: "Freemium", country: "US" },
  { name: "Apollo.io", domain: "apollo.io", task: "Find & enrich sales leads", category: "Marketing", pricing: "Freemium", country: "US" },
  { name: "Clay", domain: "clay.com", task: "Enrich & automate lead data", category: "Marketing", pricing: "Freemium", country: "US" },
  { name: "Gong", domain: "gong.io", task: "Analyze sales calls", category: "Data Analysis", pricing: "Paid", country: "US" },
  { name: "Crystal", domain: "crystalknows.com", task: "Predict personality from data", category: "Data Analysis", pricing: "Freemium", country: "US" },
  { name: "Lavender", domain: "lavender.ai", task: "Write better sales emails", category: "Marketing", pricing: "Freemium", country: "US" },
  { name: "Julius AI", domain: "julius.ai", task: "Analyze a spreadsheet", category: "Data Analysis", pricing: "Freemium", country: "US" },
  { name: "Rows", domain: "rows.com", task: "Clean a spreadsheet", category: "Data Analysis", pricing: "Freemium", country: "PT" },
  { name: "Formula Bot", domain: "formulabot.com", task: "Generate spreadsheet formulas", category: "Data Analysis", pricing: "Freemium", country: "US" },
  { name: "Obviously AI", domain: "obviously.ai", task: "Detect anomalies in data", category: "Data Analysis", pricing: "Free Trial", country: "US" },
  { name: "MonkeyLearn", domain: "monkeylearn.com", task: "Analyze text sentiment", category: "Data Analysis", pricing: "Freemium", country: "US" },
  { name: "DataRobot", domain: "datarobot.com", task: "Build a predictive model", category: "Data Analysis", pricing: "Free Trial", country: "US" },
  { name: "Scale AI", domain: "scale.com", task: "Label training data", category: "Data Analysis", pricing: "Free Trial", country: "US" },
  { name: "Weights & Biases", domain: "wandb.ai", task: "Track model experiments", category: "Coding", pricing: "Freemium", country: "US" },
  { name: "Deepgram", domain: "deepgram.com", task: "Transcribe audio via API", category: "Audio", pricing: "Free Trial", country: "US" },
  { name: "AssemblyAI", domain: "assemblyai.com", task: "Transcribe audio via API", category: "Audio", pricing: "Free Trial", country: "US" },
  { name: "Voicemod", domain: "voicemod.net", task: "Change your voice live", category: "Audio", pricing: "Freemium", country: "ES" },
  { name: "Fotor", domain: "fotor.com", task: "Edit & enhance photos", category: "Image Generation", pricing: "Freemium", country: "HK" },
  { name: "Lensa", domain: "prisma-ai.com", task: "Generate AI avatars", category: "Image Generation", pricing: "Paid", country: "US" },
];
