import { getPrisma } from '../src/lib/prisma.js';
import { RobotCategory, RobotAvailability, AutonomyLevel } from '@prisma/client';
import dotenv from 'dotenv';
dotenv.config();

const prisma = getPrisma({ DATABASE_URL: process.env.DATABASE_URL });

const ROBOTS_SEED_DATA = [
  {
    id: "tesla-optimus",
    slug: "tesla-optimus",
    name: "Tesla Optimus Gen 2",
    logoUrl: "https://www.google.com/s2/favicons?sz=64&domain=tesla.com",
    company: "Tesla",
    country: "USA",
    category: RobotCategory.HUMANOID,
    availability: RobotAvailability.IN_DEVELOPMENT,
    price: "$20,000",
    releaseDate: "2025-01-01",
    mainTask: "General purpose labor & automation",
    autonomyLevel: AutonomyLevel.HIGHLY_AUTONOMOUS,
    primaryUseCases: ["Manufacturing", "Logistics", "Household tasks"],
    websiteUrl: "https://tesla.com/optimus",
    about: "Tesla's next-generation humanoid robot featuring custom-designed actuators, 11-DoF hands with tactile sensors, 30% faster walking speed, and end-to-end trained neural networks.",
    specs: "Weight: 121 lbs. Height: 5'8\". Actuators: 28 custom. Hands: 11 DoF with tactile sensing.",
    mediaUrls: [],
  },
  {
    id: "figure-02",
    slug: "figure-02",
    name: "Figure 02",
    logoUrl: "https://www.google.com/s2/favicons?sz=64&domain=figure.ai",
    company: "Figure AI",
    country: "USA",
    category: RobotCategory.HUMANOID,
    availability: RobotAvailability.PILOT,
    price: null,
    releaseDate: "2024-08-01",
    mainTask: "Factory logistics & dexterous manipulation",
    autonomyLevel: AutonomyLevel.HIGHLY_AUTONOMOUS,
    primaryUseCases: ["Manufacturing", "Automotive assembly", "Warehouse logistics"],
    websiteUrl: "https://figure.ai",
    about: "A commercially viable humanoid robot featuring speech-to-speech AI models developed with OpenAI, 16-DoF hands, onboard vision language models, and 2.25 kWh battery.",
    specs: "Weight: 154 lbs. Height: 5'6\". Payload: 44 lbs. Operating time: 5 hours.",
    mediaUrls: [],
  },
  {
    id: "boston-dynamics-atlas",
    slug: "boston-dynamics-atlas",
    name: "All-Electric Atlas",
    logoUrl: "https://www.google.com/s2/favicons?sz=64&domain=bostondynamics.com",
    company: "Boston Dynamics",
    country: "USA",
    category: RobotCategory.HUMANOID,
    availability: RobotAvailability.IN_DEVELOPMENT,
    price: null,
    releaseDate: "2024-04-01",
    mainTask: "Heavy industrial & automotive manipulation",
    autonomyLevel: AutonomyLevel.HIGHLY_AUTONOMOUS,
    primaryUseCases: ["Automotive manufacturing", "Heavy parts handling", "Logistics"],
    websiteUrl: "https://bostondynamics.com/atlas",
    about: "Next-generation fully electric humanoid robot built for commercial applications in automotive factories, exceeding human range of motion.",
    specs: "All-electric high-torque actuators, 360-degree joint rotation, dynamic balance.",
    mediaUrls: [],
  },
  {
    id: "unitree-g1",
    slug: "unitree-g1",
    name: "Unitree G1 Humanoid Agent",
    logoUrl: "https://www.google.com/s2/favicons?sz=64&domain=unitree.com",
    company: "Unitree Robotics",
    country: "China",
    category: RobotCategory.HUMANOID,
    availability: RobotAvailability.COMMERCIALLY_AVAILABLE,
    price: "$16,000",
    releaseDate: "2024-05-01",
    mainTask: "AI research & general assistance",
    autonomyLevel: AutonomyLevel.HIGHLY_AUTONOMOUS,
    primaryUseCases: ["AI embodiment research", "Education", "Light assembly"],
    websiteUrl: "https://unitree.com/g1",
    about: "An affordable 127cm humanoid robot featuring 23–43 joint motors, force-controlled dexterous hands, LiDAR + depth camera sensing, and reinforcement learning motion control.",
    specs: "Weight: 35 kg. Height: 127 cm. Max torque: 120 N.m. 3D LiDAR + RealSense camera.",
    mediaUrls: [],
  },
  {
    id: "unitree-h1",
    slug: "unitree-h1",
    name: "Unitree H1",
    logoUrl: "https://www.google.com/s2/favicons?sz=64&domain=unitree.com",
    company: "Unitree Robotics",
    country: "China",
    category: RobotCategory.HUMANOID,
    availability: RobotAvailability.COMMERCIALLY_AVAILABLE,
    price: "$90,000",
    releaseDate: "2023-12-01",
    mainTask: "High-speed bipedal locomotion",
    autonomyLevel: AutonomyLevel.HIGHLY_AUTONOMOUS,
    primaryUseCases: ["Logistics", "Inspection", "Research"],
    websiteUrl: "https://unitree.com/h1",
    about: "Full-size general-purpose humanoid robot capable of running at 3.3 m/s (world record for humanoid), backflips, and robust terrain navigation.",
    specs: "Weight: 47 kg. Height: 180 cm. Speed: 3.3 m/s. Max knee torque: 360 N.m.",
    mediaUrls: [],
  },
  {
    id: "boston-dynamics-spot",
    slug: "boston-dynamics-spot",
    name: "Boston Dynamics Spot Enterprise",
    logoUrl: "https://www.google.com/s2/favicons?sz=64&domain=bostondynamics.com",
    company: "Boston Dynamics",
    country: "USA",
    category: RobotCategory.MOBILE,
    availability: RobotAvailability.COMMERCIALLY_AVAILABLE,
    price: "$74,500",
    releaseDate: "2020-06-01",
    mainTask: "Industrial inspection & site monitoring",
    autonomyLevel: AutonomyLevel.FULLY_AUTONOMOUS,
    primaryUseCases: ["Thermal inspection", "Gas leak detection", "Radiation sensing", "Site security"],
    websiteUrl: "https://bostondynamics.com/spot",
    about: "The industry standard quadruped robot for autonomous inspection, equipped with 360° cameras, self-charging dock, payload expansion port, and API control.",
    specs: "Weight: 32.7 kg. Max payload: 14 kg. Speed: 1.6 m/s. Battery life: 90 mins.",
    mediaUrls: [],
  },
  {
    id: "unitree-go2",
    slug: "unitree-go2",
    name: "Unitree Go2 Pro Quadruped",
    logoUrl: "https://www.google.com/s2/favicons?sz=64&domain=unitree.com",
    company: "Unitree Robotics",
    country: "China",
    category: RobotCategory.MOBILE,
    availability: RobotAvailability.COMMERCIALLY_AVAILABLE,
    price: "$2,800",
    releaseDate: "2023-07-01",
    mainTask: "Robotics research, companion & mapping",
    autonomyLevel: AutonomyLevel.HIGHLY_AUTONOMOUS,
    primaryUseCases: ["Inspection", "SLAMS mapping", "Education", "Search and rescue"],
    websiteUrl: "https://unitree.com/go2",
    about: "Equipped with ultra-wide 4D LiDAR L1, GPT integration for natural conversation, 12 high-power knee motors, and 4G/Wi-Fi remote connectivity.",
    specs: "Weight: 15 kg. Speed: 3.5 m/s. Battery: 8000 mAh. 4D LiDAR sensor.",
    mediaUrls: [],
  },
  {
    id: "universal-robots-ur10e",
    slug: "universal-robots-ur10e",
    name: "Universal Robots UR10e Cobot",
    logoUrl: "https://www.google.com/s2/favicons?sz=64&domain=universal-robots.com",
    company: "Universal Robots",
    country: "Denmark",
    category: RobotCategory.INDUSTRIAL,
    availability: RobotAvailability.COMMERCIALLY_AVAILABLE,
    price: "$45,000",
    releaseDate: "2018-06-01",
    mainTask: "Palletizing, CNC machine tending & welding",
    autonomyLevel: AutonomyLevel.SEMI_AUTONOMOUS,
    primaryUseCases: ["Palletizing", "Machine tending", "Packaging", "Quality inspection"],
    websiteUrl: "https://universal-robots.com",
    about: "Versatile collaborative robot arm with 12.5 kg payload and 1300 mm reach, featuring built-in force/torque sensor and intuitive teach pendant programming.",
    specs: "Reach: 1300 mm. Payload: 12.5 kg. Weight: 33.5 kg. Repeatability: +/- 0.05 mm.",
    mediaUrls: [],
  },
  {
    id: "intuitive-da-vinci-5",
    slug: "intuitive-da-vinci-5",
    name: "Intuitive da Vinci 5 Surgical Robot",
    logoUrl: "https://www.google.com/s2/favicons?sz=64&domain=intuitive.com",
    company: "Intuitive Surgical",
    country: "USA",
    category: RobotCategory.HEALTHCARE,
    availability: RobotAvailability.COMMERCIALLY_AVAILABLE,
    price: "$2,200,000",
    releaseDate: "2024-03-01",
    mainTask: "Robotic-assisted minimally invasive surgery",
    autonomyLevel: AutonomyLevel.ASSISTED,
    primaryUseCases: ["General surgery", "Urology", "Gynecology", "Cardiothoracic"],
    websiteUrl: "https://intuitive.com",
    about: "Next-gen surgical system with 10,000x the computing power of da Vinci Xi, featuring true force-feedback sensation, 3D 4K visualization, and AI operative analytics.",
    specs: "Force-sensing technology, 4-arm design, 3D high-definition endoscope, sub-millimeter precision.",
    mediaUrls: [],
  },
  {
    id: "starship-delivery",
    slug: "starship-delivery",
    name: "Starship Autonomous Delivery Robot",
    logoUrl: "https://www.google.com/s2/favicons?sz=64&domain=starship.xyz",
    company: "Starship Technologies",
    country: "USA",
    category: RobotCategory.SERVICE,
    availability: RobotAvailability.COMMERCIALLY_AVAILABLE,
    price: null,
    releaseDate: "2018-01-01",
    mainTask: "Last-mile sidewalk food & parcel delivery",
    autonomyLevel: AutonomyLevel.FULLY_AUTONOMOUS,
    primaryUseCases: ["Campus delivery", "Neighborhood grocery delivery", "Parcel drop-off"],
    websiteUrl: "https://starship.xyz",
    about: "6-wheeled autonomous sidewalk robot that has completed over 6 million commercial deliveries across university campuses and cities worldwide.",
    specs: "Weight: 23 kg. Speed: 6 km/h. Cargo: 10 kg (3 grocery bags). 12 cameras, ultrasonic sensors, GPS.",
    mediaUrls: [],
  },
  {
    id: "john-deere-8r",
    slug: "john-deere-8r",
    name: "John Deere Autonomous 8R Tractor",
    logoUrl: "https://www.google.com/s2/favicons?sz=64&domain=deere.com",
    company: "John Deere",
    country: "USA",
    category: RobotCategory.AGRICULTURAL,
    availability: RobotAvailability.COMMERCIALLY_AVAILABLE,
    price: "$500,000",
    releaseDate: "2022-01-01",
    mainTask: "24/7 autonomous tillage & crop field preparation",
    autonomyLevel: AutonomyLevel.FULLY_AUTONOMOUS,
    primaryUseCases: ["Chisel plowing", "Tillage", "Precision planting"],
    websiteUrl: "https://deere.com",
    about: "Production-ready autonomous tractor equipped with 6 pairs of stereo cameras, deep neural net classification, and geofenced smartphone control for 24/7 tillage without an operator in the cab.",
    specs: "Power: 410 HP. 12 stereo cameras with 360-degree obstacle detection. Precision GPS RTK +/- 2.5 cm.",
    mediaUrls: [],
  },
  {
    id: "skydio-x10",
    slug: "skydio-x10",
    name: "Skydio X10 Enterprise AI Drone",
    logoUrl: "https://www.google.com/s2/favicons?sz=64&domain=skydio.com",
    company: "Skydio",
    country: "USA",
    category: RobotCategory.DRONE,
    availability: RobotAvailability.COMMERCIALLY_AVAILABLE,
    price: "$20,000",
    releaseDate: "2023-10-01",
    mainTask: "Autonomous aerial mapping & infrastructure inspection",
    autonomyLevel: AutonomyLevel.FULLY_AUTONOMOUS,
    primaryUseCases: ["Power grid inspection", "First responder search", "3D building scan"],
    websiteUrl: "https://skydio.com",
    about: "Enterprise drone powered by NVIDIA Jetson Orin compute, featuring 360-degree night-time obstacle avoidance, telephoto and radiometric thermal cameras, and 5G cellular connectivity.",
    specs: "Compute: NVIDIA Jetson Orin. Flight time: 40 min. Sensor: 64MP wide, 48MP zoom, FLIR Boson+ thermal.",
    mediaUrls: [],
  },
  {
    id: "amazon-astro",
    slug: "amazon-astro",
    name: "Amazon Astro for Business",
    logoUrl: "https://www.google.com/s2/favicons?sz=64&domain=amazon.com",
    company: "Amazon",
    country: "USA",
    category: RobotCategory.COMPANION,
    availability: RobotAvailability.COMMERCIALLY_AVAILABLE,
    price: "$1,599",
    releaseDate: "2021-09-01",
    mainTask: "Home monitoring & commercial security patrol",
    autonomyLevel: AutonomyLevel.HIGHLY_AUTONOMOUS,
    primaryUseCases: ["Night security patrol", "Elderly monitoring", "Home automation hub"],
    websiteUrl: "https://amazon.com/astro",
    about: "Autonomous household and business robot equipped with a periscope camera, visual ID, intelligent SLAM mapping, and Alexa smart home controls.",
    specs: "Periscope camera with 42-inch reach. 10.1-inch HD touchscreen display. 2-way audio.",
    mediaUrls: [],
  }
];

async function seed() {
  console.log('Seeding robots into database...');
  for (const r of ROBOTS_SEED_DATA) {
    await prisma.robot.upsert({
      where: { slug: r.slug },
      update: r,
      create: r,
    });
    console.log(`✓ Seeded: ${r.name}`);
  }
  console.log(`Seeded ${ROBOTS_SEED_DATA.length} robots successfully!`);
}

seed()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
