-- CreateEnum
CREATE TYPE "ToolCategoryEnum" AS ENUM ('WRITING', 'IMAGE_GENERATION', 'VIDEO_GENERATION', 'AUDIO', 'CHATBOTS', 'CODING', 'MARKETING', 'PRODUCTIVITY', 'BUSINESS', 'EDUCATION', 'AGENTS', 'PRESENTATIONS', 'THREE_D_GENERATION', 'NO_CODE_AI_BUILDERS', 'WORKFLOW_AUTOMATION');

-- AlterTable
ALTER TABLE "Tool" ADD COLUMN     "toolCategories" "ToolCategoryEnum"[] DEFAULT ARRAY[]::"ToolCategoryEnum"[];
