import type { CollectionListItem } from "@/lib/types";

export const mockCollections: CollectionListItem[] = [
  {
    id: "1",
    name: "Best AI Tools",
    slug: "best-ai-tools",
    description: "A curated collection of the best AI tools across every category.",
    isFeatured: true,
    creatorType: "EDITORIAL",
    toolCount: 148,
    updatedAt: "2026-07-18T12:00:00Z",
    creator: {
      id: "1",
      name: "OpenTools Editorial",
      image: null,
    },
    categories: [
      { categoryName: "Productivity" },
      { categoryName: "AI" },
      { categoryName: "Featured" },
    ],
    _count: {
      relatedModels: 18,
      relatedCompanies: 12,
    },
  },
  {
    id: "2",
    name: "AI Coding Assistants",
    slug: "ai-coding-assistants",
    description: "Everything developers need to code faster with AI.",
    isFeatured: true,
    creatorType: "EDITORIAL",
    toolCount: 82,
    updatedAt: "2026-07-16T09:20:00Z",
    creator: {
      id: "2",
      name: "DevHub",
      image: null,
    },
    categories: [
      { categoryName: "Development" },
      { categoryName: "Programming" },
    ],
    _count: {
      relatedModels: 9,
      relatedCompanies: 6,
    },
  },
  {
    id: "3",
    name: "Marketing Toolkit",
    slug: "marketing-toolkit",
    description: "AI tools for social media, SEO, ads and content marketing.",
    isFeatured: false,
    creatorType: "COMMUNITY",
    toolCount: 61,
    updatedAt: "2026-07-10T15:00:00Z",
    creator: {
      id: "3",
      name: "Sarah Chen",
      image: null,
    },
    categories: [
      { categoryName: "Marketing" },
      { categoryName: "SEO" },
    ],
    _count: {
      relatedModels: 5,
      relatedCompanies: 7,
    },
  },
  {
    id: "4",
    name: "Designer's AI Stack",
    slug: "designers-ai-stack",
    description: "Curated AI tools for UI, UX, graphics and branding.",
    isFeatured: false,
    creatorType: "COMMUNITY",
    toolCount: 44,
    updatedAt: "2026-07-14T11:30:00Z",
    creator: {
      id: "4",
      name: "Emily Carter",
      image: null,
    },
    categories: [
      { categoryName: "Design" },
      { categoryName: "Creativity" },
    ],
    _count: {
      relatedModels: 6,
      relatedCompanies: 5,
    },
  },
  {
    id: "5",
    name: "AI Research Papers",
    slug: "ai-research-papers",
    description: "Useful tools for reading, summarizing and organizing research.",
    isFeatured: false,
    creatorType: "EDITORIAL",
    toolCount: 35,
    updatedAt: "2026-07-12T13:00:00Z",
    creator: {
      id: "5",
      name: "OpenResearch",
      image: null,
    },
    categories: [
      { categoryName: "Research" },
      { categoryName: "Education" },
    ],
    _count: {
      relatedModels: 7,
      relatedCompanies: 3,
    },
  },
  {
    id: "6",
    name: "Video Creation Suite",
    slug: "video-creation-suite",
    description: "AI video editing, generation and animation tools.",
    isFeatured: true,
    creatorType: "EDITORIAL",
    toolCount: 73,
    updatedAt: "2026-07-19T08:00:00Z",
    creator: {
      id: "6",
      name: "Media AI",
      image: null,
    },
    categories: [
      { categoryName: "Video" },
      { categoryName: "Content" },
    ],
    _count: {
      relatedModels: 10,
      relatedCompanies: 8,
    },
  },
  {
    id: "7",
    name: "Startup Essentials",
    slug: "startup-essentials",
    description: "AI products every startup founder should know.",
    isFeatured: false,
    creatorType: "COMMUNITY",
    toolCount: 54,
    updatedAt: "2026-07-09T17:45:00Z",
    creator: {
      id: "7",
      name: "Rohan Mehta",
      image: null,
    },
    categories: [
      { categoryName: "Business" },
      { categoryName: "Startups" },
    ],
    _count: {
      relatedModels: 4,
      relatedCompanies: 6,
    },
  },
  {
    id: "8",
    name: "Student Productivity",
    slug: "student-productivity",
    description: "Study smarter with note-taking, tutoring and revision tools.",
    isFeatured: false,
    creatorType: "COMMUNITY",
    toolCount: 40,
    updatedAt: "2026-07-11T10:00:00Z",
    creator: {
      id: "8",
      name: "Aisha Khan",
      image: null,
    },
    categories: [
      { categoryName: "Education" },
      { categoryName: "Students" },
    ],
    _count: {
      relatedModels: 5,
      relatedCompanies: 4,
    },
  },
  {
    id: "9",
    name: "AI for Writers",
    slug: "ai-for-writers",
    description: "Writing assistants, grammar tools and storytelling AI.",
    isFeatured: true,
    creatorType: "EDITORIAL",
    toolCount: 69,
    updatedAt: "2026-07-17T14:00:00Z",
    creator: {
      id: "9",
      name: "WriteBetter",
      image: null,
    },
    categories: [
      { categoryName: "Writing" },
      { categoryName: "Content" },
    ],
    _count: {
      relatedModels: 8,
      relatedCompanies: 7,
    },
  },
  {
    id: "10",
    name: "No-Code AI Builders",
    slug: "no-code-ai-builders",
    description: "Build AI apps without writing code.",
    isFeatured: false,
    creatorType: "EDITORIAL",
    toolCount: 58,
    updatedAt: "2026-07-13T18:20:00Z",
    creator: {
      id: "10",
      name: "Builder Labs",
      image: null,
    },
    categories: [
      { categoryName: "No-Code" },
      { categoryName: "Automation" },
    ],
    _count: {
      relatedModels: 6,
      relatedCompanies: 5,
    },
  },
];